# Generated by Django 3.0.5 on 2020-04-23 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='amout')),
                ('priceOrder', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pro', models.CharField(max_length=500)),
                ('price_pro', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('img_pro', models.ImageField(upload_to='imgProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname_user', models.CharField(max_length=20, verbose_name='Product Name')),
                ('lastname_user', models.CharField(max_length=20, verbose_name='Product Name')),
                ('address_user', models.TextField(max_length=300, verbose_name='Address')),
                ('phone_user', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('amount', models.IntegerField(default=0, verbose_name='amout')),
                ('message', models.TextField(max_length=300, verbose_name='Message')),
                ('Order', models.ManyToManyField(through='ecom.Order', to='ecom.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.Transaction'),
        ),
    ]
