# Generated by Django 3.0.5 on 2020-04-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='firstname_user',
            field=models.CharField(max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='lastname_user',
            field=models.CharField(max_length=20, verbose_name='last name'),
        ),
    ]
