# Generated by Django 3.0.5 on 2020-04-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20200428_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='id_trans',
            field=models.IntegerField(default=0, verbose_name='id_trans'),
        ),
    ]
