# Generated by Django 3.0.5 on 2020-05-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_transaction_id_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_trans',
            field=models.IntegerField(verbose_name='id_trans'),
        ),
    ]
