# Generated by Django 3.0.5 on 2020-05-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20200501_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
