# Generated by Django 3.0.5 on 2020-05-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_remove_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_trans',
            field=models.IntegerField(default=1, verbose_name='id_trans'),
        ),
    ]
