# Generated by Django 3.0.5 on 2020-05-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20200508_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amounts',
            field=models.IntegerField(default=10, verbose_name='amouts'),
            preserve_default=False,
        ),
    ]
