# Generated by Django 3.0.5 on 2020-05-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20200505_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_trans',
            field=models.IntegerField(verbose_name='id_trans'),
        ),
    ]
