# Generated by Django 3.0.5 on 2020-05-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_transaction_amounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amounts',
        ),
    ]
